### ISSUE TITLE
Fails to build with SDL 1.2.15

### ISSUE THREAD

**Issue by Mailaender** [bjaraujo/Bombermaaan#46]
```
/run/build/bombermaaan/trunk/src/CVideoSDL.cpp: In member function ‘bool CVideoSDL::Create(int, int, int, bool)’:
/run/build/bombermaaan/trunk/src/CVideoSDL.cpp:171:99: error: ‘SDL_VIDEO_OPENGL’ was not declared in this scope
  171 |         m_pPrimary = SDL_SetVideoMode(m_Width, m_Height, m_Depth, SDL_HWSURFACE | SDL_DOUBLEBUF | SDL_VIDEO_OPENGL);
      |                                                                                                   ^~~~~~~~~~~~~~~~
/run/build/bombermaaan/trunk/src/CVideoSDL.cpp:189:99: error: ‘SDL_VIDEO_OPENGL’ was not declared in this scope
  189 |         m_pPrimary = SDL_SetVideoMode(m_Width, m_Height, m_Depth, SDL_HWSURFACE | SDL_DOUBLEBUF | SDL_VIDEO_OPENGL | SDL_FULLSCREEN);
      |                                                                                                   ^~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/Bombermaaan.dir/build.make:860: src/CMakeFiles/Bombermaaan.dir/CVideoSDL.cpp.o] Error 1

```

**Comment by Mailaender** [comment]
Sorry, I was missing glu.

**Comment by Mailaender** [comment]
Same error happens with sdl12-compat version 1.2.52.
